name: ChannelTabsConfiguration
type: class
category:
memory_category: Instances
summary: |
  Configures properties of the optional channel tabs in the default chat window.
description: |
  Configures properties of the optional channel tabs in the default chat window.
  It is parented to `Class.TextChatService`.

  To learn more, see [Customizing Text Chat](../../../chat/customizing-in-experience-text-chat.md).
code_samples: []
inherits:
  - TextChatConfigurations
tags:
  - NotCreatable
deprecation_message: ''
properties:
  - name: ChannelTabsConfiguration.AbsolutePosition
    summary: |
      Actual screen position of the channel tab bar, in pixels.
    description: |
      Read-only property that provides the screen position of the channel tab bar in pixels. Behaves similarly to `Class.GuiBase2d.AbsolutePosition`.
    code_samples: []
    type: Vector2
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Data
    serialization:
      can_load: false
      can_save: false
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.AbsoluteSize
    summary: |
      Actual screen size of the channel tab bar, in pixels.
    description: |
      Read-only property that provides the screen size of the channel tab bar in pixels. Behaves similarly to `Class.GuiBase2d.AbsoluteSize`.
    code_samples: []
    type: Vector2
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Data
    serialization:
      can_load: false
      can_save: false
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.BackgroundColor3
    summary: |
      Background color of the channel tabs.
    description: |
      Background color of the channel tabs. If the background color is not
      overridden, this value will respect the user's
      `Class.GuiService.PreferredTransparency` by making the menu more gray as
      the transparency of the menu decreases. Default value is
      `Datatype.Color3|Color3.new(25, 27, 29)`.
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.BackgroundTransparency
    summary: |
      Background transparency of the channel tabs.
    description: |
      Background transparency of the channel tabs as a number between `0` and
      `1`. This value is multiplied with the user's
      `Class.GuiService.PreferredTransparency` to create the effective
      background transparency used by the channel tabs, which may be more opaque
      than this value set here. Default value is `0`.
    code_samples: []
    type: double
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.Enabled
    summary: |
      Whether to show the channel tabs.
    description: |
      Whether to show the channel tabs. Set to `false` to hide.
    code_samples: []
    type: bool
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Behavior
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.FontFace
    summary: |
      Font used to render text in the channel tabs.
    description: |
      Font used to render text in the channel tabs. Default is `Enum.Font.BuilderSansBold`.
    code_samples: []
    type: Font
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.HoverBackgroundColor3
    summary: |
      Background color of a channel tab when hovering over it.
    description: |
      Background color of a channel tab when hovering over it. Default value is
      `Datatype.Color3|Color3.new(125, 125, 125)`.
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.SelectedTabTextColor3
    summary: |
      Color of text in a selected tab.
    description: |
      Color of text in a selected tab. Default value is
      `Datatype.Color3|Color3.new(255, 255, 255)`.
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.TextColor3
    summary: |
      Color of text in an unselected tab.
    description: |
      Color of text in an unselected tab. Default value is
      `Datatype.Color3|Color3.new(175, 175, 175)`.
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.TextSize
    summary: |
      Size of the text in channel tabs.
    description: |
      Size of the text in channel tabs. Default value is `14`.
    code_samples: []
    type: int64
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.TextStrokeColor3
    summary: |
      Color of the text stroke for text in channel tabs.
    description: |
      Color of the text stroke for text in channel tabs. Default value is
      `Datatype.Color3|Color3.new(0, 0, 0)`.
    code_samples: []
    type: Color3
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
  - name: ChannelTabsConfiguration.TextStrokeTransparency
    summary: |
      Transparency of the text stroke for text in channel tabs.
    description: |
      Transparency of the text stroke for text in channel tabs. Default value is
      `1`.
    code_samples: []
    type: double
    tags: []
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Appearance
    serialization:
      can_load: true
      can_save: true
    capabilities:
      - Chat
    writeCapabilities: []
methods: []
events: []
callbacks: []
