name: ConfigSnapshot
type: class
category:
memory_category: Instances
summary: ''
description: ''
code_samples: []
inherits:
  - Object
tags:
  - NotCreatable
  - NotReplicated
deprecation_message: ''
properties:
  - name: ConfigSnapshot.Error
    summary: ''
    description: ''
    code_samples: []
    type: ConfigSnapshotErrorState
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Data
    serialization:
      can_load: false
      can_save: true
    capabilities: []
    writeCapabilities: []
  - name: ConfigSnapshot.Outdated
    summary: ''
    description: ''
    code_samples: []
    type: boolean
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Data
    serialization:
      can_load: false
      can_save: true
    capabilities: []
    writeCapabilities: []
methods:
  - name: ConfigSnapshot:GetValue
    summary: ''
    description: ''
    code_samples: []
    parameters:
      - name: key
        type: string
        default: ''
        summary: ''
      - name: defaultValue
        type: Variant
        default: ''
        summary: ''
    returns:
      - type: Variant
        summary: ''
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
  - name: ConfigSnapshot:GetValueChangedSignal
    summary: ''
    description: ''
    code_samples: []
    parameters:
      - name: key
        type: string
        default: ''
        summary: ''
    returns:
      - type: RBXScriptSignal
        summary: ''
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
  - name: ConfigSnapshot:Refresh
    summary: ''
    description: ''
    code_samples: []
    parameters: []
    returns:
      - type: ()
        summary: ''
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
events:
  - name: ConfigSnapshot.UpdateAvailable
    summary: ''
    description: ''
    code_samples: []
    parameters: []
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
callbacks: []
