name: GoogleAnalyticsConfiguration
type: class
memory_category: Instances
summary: ''
description: |
  **GoogleAnalyticsConfiguration** is a settings class that stores a unique
  identifier for your client. It is used by Roblox to persistently record
  analytics from the client.
code_samples: []
inherits:
  - Instance
tags:
  - NotCreatable
  - Service
deprecation_message: ''
properties: []
methods: []
events: []
callbacks: []
